# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 350)
        Dialog.setMaximumSize(QtCore.QSize(300, 350))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.labelDataBits = QtWidgets.QLabel(Dialog)
        self.labelDataBits.setObjectName("labelDataBits")
        self.gridLayout.addWidget(self.labelDataBits, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.labelBaudRate = QtWidgets.QLabel(Dialog)
        self.labelBaudRate.setObjectName("labelBaudRate")
        self.gridLayout.addWidget(self.labelBaudRate, 1, 0, 1, 1)
        self.labelStopBit = QtWidgets.QLabel(Dialog)
        self.labelStopBit.setObjectName("labelStopBit")
        self.gridLayout.addWidget(self.labelStopBit, 4, 0, 1, 1)
        self.labelParityBit = QtWidgets.QLabel(Dialog)
        self.labelParityBit.setObjectName("labelParityBit")
        self.gridLayout.addWidget(self.labelParityBit, 3, 0, 1, 1)
        self.comboBoxStopBit = QtWidgets.QComboBox(Dialog)
        self.comboBoxStopBit.setObjectName("comboBoxStopBit")
        self.comboBoxStopBit.addItem("")
        self.comboBoxStopBit.addItem("")
        self.comboBoxStopBit.addItem("")
        self.gridLayout.addWidget(self.comboBoxStopBit, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.comboBoxParityBit = QtWidgets.QComboBox(Dialog)
        self.comboBoxParityBit.setObjectName("comboBoxParityBit")
        self.comboBoxParityBit.addItem("")
        self.comboBoxParityBit.addItem("")
        self.comboBoxParityBit.addItem("")
        self.comboBoxParityBit.addItem("")
        self.comboBoxParityBit.addItem("")
        self.gridLayout.addWidget(self.comboBoxParityBit, 3, 2, 1, 1)
        self.comboBoxBaudRate = QtWidgets.QComboBox(Dialog)
        self.comboBoxBaudRate.setObjectName("comboBoxBaudRate")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.comboBoxBaudRate.addItem("")
        self.gridLayout.addWidget(self.comboBoxBaudRate, 1, 2, 1, 1)
        self.labelCOMPort = QtWidgets.QLabel(Dialog)
        self.labelCOMPort.setObjectName("labelCOMPort")
        self.gridLayout.addWidget(self.labelCOMPort, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.comboBoxDataBits = QtWidgets.QComboBox(Dialog)
        self.comboBoxDataBits.setObjectName("comboBoxDataBits")
        self.comboBoxDataBits.addItem("")
        self.comboBoxDataBits.addItem("")
        self.comboBoxDataBits.addItem("")
        self.comboBoxDataBits.addItem("")
        self.gridLayout.addWidget(self.comboBoxDataBits, 2, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelDataBits.setText(_translate("Dialog", "Data bits:"))
        self.labelBaudRate.setText(_translate("Dialog", "Baud rate:"))
        self.labelStopBit.setText(_translate("Dialog", "Stop bit:"))
        self.labelParityBit.setText(_translate("Dialog", "Parity bit:"))
        self.comboBoxStopBit.setItemText(0, _translate("Dialog", "1"))
        self.comboBoxStopBit.setItemText(1, _translate("Dialog", "1.5"))
        self.comboBoxStopBit.setItemText(2, _translate("Dialog", "2"))
        self.comboBoxParityBit.setItemText(0, _translate("Dialog", "None"))
        self.comboBoxParityBit.setItemText(1, _translate("Dialog", "Odd"))
        self.comboBoxParityBit.setItemText(2, _translate("Dialog", "Even"))
        self.comboBoxParityBit.setItemText(3, _translate("Dialog", "Mark"))
        self.comboBoxParityBit.setItemText(4, _translate("Dialog", "Space"))
        self.comboBoxBaudRate.setCurrentText(_translate("Dialog", "57600"))
        self.comboBoxBaudRate.setItemText(0, _translate("Dialog", "9600"))
        self.comboBoxBaudRate.setItemText(1, _translate("Dialog", "19200"))
        self.comboBoxBaudRate.setItemText(2, _translate("Dialog", "57600"))
        self.comboBoxBaudRate.setItemText(3, _translate("Dialog", "115200"))
        self.labelCOMPort.setText(_translate("Dialog", "COM Port:"))
        self.comboBoxDataBits.setCurrentText(_translate("Dialog", "8"))
        self.comboBoxDataBits.setItemText(0, _translate("Dialog", "5"))
        self.comboBoxDataBits.setItemText(1, _translate("Dialog", "6"))
        self.comboBoxDataBits.setItemText(2, _translate("Dialog", "7"))
        self.comboBoxDataBits.setItemText(3, _translate("Dialog", "8"))
        self.pushButton.setText(_translate("Dialog", "OK"))
